[[redirects]]

  # 设置blog的404
  from = "/blog/*"
  to = "/blog/index.html"
  status = 200
  
[[redirects]]

  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run deploy" 